apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: default  # Remplacez par le namespace où Nextcloud est installé, si différent
spec:
  accessModes:
    - ReadWriteOnce  # Ceci permet à la volume d'être lu/écrit par un seul nœud à la fois
  resources:
    requests:
      storage: 8Gi  # Ceci spécifie la taille du volume
  # storageClassName: ""  # Décommentez et spécifiez le nom de la classe de stockage si nécessaire
